# drop_duplicates

#### The drop_duplicates() function in Pandas is used to remove duplicate rows from a DataFrame. It helps in identifying and eliminating rows where all the values across columns are identical or where specified columns have duplicate values.

#### Arguments
#### subset=None, keep='first', inplace=False, ignore_index=False

In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({'A': [1, 2, 2, 3, 4],
        'B': ['x', 'y', 'y', 'z', 'z'],
        'C': ['a', 'b', 'b', 'c', 'c']})

In [3]:
df

   A  B  C
0  1  x  a
1  2  y  b
2  2  y  b
3  3  z  c
4  4  z  c

#### Using Argument: subset
subset: Columns to consider for identifying duplicates.None is given as default which means it considers all columns.Returns a dataframe

In [4]:
# Removing duplicates based on a subset of columns (A and B)
df.drop_duplicates(subset=['A', 'B'])

   A  B  C
0  1  x  a
1  2  y  b
3  3  z  c
4  4  z  c

#### Using Argument: keep
keep: Specifies which duplicate to keep. Returns a dataframe

#### Options are, 
1)'first' (default)
2)'last' 
3) False - drops all duplicates

In [5]:
df1 = pd.DataFrame({'A': [1, 2, 2, 3, 4],
        'B': ['x', 'y', 'y', 'z', 'z']})

In [6]:
df1

   A  B
0  1  x
1  2  y
2  2  y
3  3  z
4  4  z

In [7]:
# Removing duplicates and keeping the last occurrence
df1.drop_duplicates(keep='last')

   A  B
0  1  x
2  2  y
3  3  z
4  4  z

In [8]:
# Removing duplicates and keeping the last occurrence
df.drop_duplicates(keep='first')

   A  B  C
0  1  x  a
1  2  y  b
3  3  z  c
4  4  z  c

In [9]:
# Removing duplicates and keeping the last occurrence
df.drop_duplicates(keep=False)

   A  B  C
0  1  x  a
3  3  z  c
4  4  z  c

#### Using argument: inplace
inplace: If True, performs the operation in the original dataframe and it returns 'None'.

In [10]:
df3 = pd.DataFrame( {'A': [1, 2, 2, 3, 3, 3, 4],
        'B': ['x', 'y', 'y', 'z','z','z', 'z']})

In [11]:
df3

   A  B
0  1  x
1  2  y
2  2  y
3  3  z
4  3  z
5  3  z
6  4  z

In [12]:
# Removing duplicates in place
df3.drop_duplicates(inplace=True)

# it returns none

In [13]:
df3

   A  B
0  1  x
1  2  y
3  3  z
6  4  z

#### Using argument: ignore_index
ignore_index: If True, the resulting DataFrame will have a new RangeIndex,ignoring the original dataframe index.
Returns a dataframe

In [14]:
df4 = pd.DataFrame( {'A': [1, 2, 2, 3, 3, 3, 4],
        'B': ['x', 'y', 'y', 'z','z','z', 'z']})

In [15]:
df4

   A  B
0  1  x
1  2  y
2  2  y
3  3  z
4  3  z
5  3  z
6  4  z

In [16]:
# Removing duplicates and resetting index
df4.drop_duplicates(ignore_index=True)

   A  B
0  1  x
1  2  y
2  3  z
3  4  z