### DataFrame.add_suffix(suffix, axis=None)

1. Suffix labels with string suffix.
2. For Series, the row labels are suffixed.
3. For DataFrame, the column labels are suffixed.

### Parameters:
suffix:str,The string to add after each label.

axis:{0 or ‘index’, 1 or ‘columns’, None}, default None
Axis to add suffix on

### Returns:
New Series or DataFrame with updated labels.

In [2]:
import pandas as pd
s = pd.Series([1, 2, 3, 4])
s

0    1
1    2
2    3
3    4
dtype: int64

In [3]:
s.add_suffix('_item')

0_item    1
1_item    2
2_item    3
3_item    4
dtype: int64

In [4]:
df = pd.DataFrame({'A': [1, 2, 3, 4], 'B': [3, 4, 5, 6]})
df

   A  B
0  1  3
1  2  4
2  3  5
3  4  6

In [6]:
df.add_suffix('_col',axis=0)
df.add_suffix('_col',axis=1)

   A_col  B_col
0      1      3
1      2      4
2      3      5
3      4      6