### DataFrame.add_prefix(prefix, axis=None)

1. Prefix labels with string prefix.
2. For Series, the row labels are prefixed.
3. For DataFrame, the column labels are prefixed.

### Parameters:
prefix:str,The string to add before each label.

axis{0 or ‘index’, 1 or ‘columns’, None}, default None
Axis to add prefix on

### Returns:
New Series or DataFrame with updated labels.

In [4]:
import pandas as pd
s = pd.Series([1, 2, 3, 4])
s

0    1
1    2
2    3
3    4
dtype: int64

In [12]:
s.add_prefix('item_',axis=0)

item_0    1
item_1    2
item_2    3
item_3    4
dtype: int64

In [6]:
df = pd.DataFrame({'A': [1, 2, 3, 4], 'B': [3, 4, 5, 6]})
df

   A  B
0  1  3
1  2  4
2  3  5
3  4  6

In [13]:
df.add_prefix('col_',axis=0)
df.add_prefix('col_',axis=1)

   col_A  col_B
0      1      3
1      2      4
2      3      5
3      4      6